version: '2'

services:
    webserver:
        image: thepaperlessproject/paperless
        restart: always
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8080:8000"
        volumes:
            - paperless_data:/usr/src/paperless/data:nocopy
            - paperless_media:/usr/src/paperless/media:nocopy
            - paperless_consume:/consume:nocopy
            - paperless_export:/export:nocopy
        environment:
            - PAPERLESS_OCR_LANGUAGES=eng
            - USERMAP_UID=1020
            - USERMAP_GID=1000
        command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]

    consumer:
        image: thepaperlessproject/paperless
        restart: always
        depends_on:
            - webserver
        volumes:
            - paperless_data:/usr/src/paperless/data:nocopy
            - paperless_media:/usr/src/paperless/media:nocopy
            - paperless_consume:/consume:nocopy
            - paperless_export:/export:nocopy
        command: ["document_consumer"]
        environment:
            - PAPERLESS_OCR_LANGUAGES=eng
            - USERMAP_UID=1020
            - USERMAP_GID=1000
            - PAPERLESS_CONVERT_MEMORY_LIMIT=32000000
            - PAPERLESS_CONVERT_TMPDIR=/var/tmp
        tmpfs:
            - /tmp

    rsync:
        image: stefda/rsync
        restart: always
        volumes:
            - paperless_consume:/volume
        tmpfs:
            - /tmp
        ports:
            - "873:873"

volumes:
    paperless_data:
        external: true
    paperless_consume:
        external: true
    paperless_media:
        external: true
    paperless_export:
        external: true
